on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: comment
      uses: zimagen/hello-world-javascript-action@v1.3
      with:
        repoToken: ${{ secrets.YOUR_GITHUB_TOKEN }}
