on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: comment
      uses: zimagen/comment-image-of-times-hiro@v1.0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
